### PR TITLE
Fix xref64 for case of addr & 0xfff == 0

### PR DESCRIPTION
**Pull request by sbingner**
If the address being looked for had no value for PAGEOFF it would return the first ref to the PAGE.  This fixes that.

### CODE REVIEW

**Comment by xerub** [comment]
If the address being looked for had no value for PAGEOFF, would not be still an XREF?
Do you have an example/usecase where current behavior is wrong?

**Comment by sbingner** [comment]
When there is an address anywhere in the same page referenced before the ref you’re looking for where ADR was 0, it would see that the register had the target address in it as soon as the ADRP instruction was parsed without seeing that the next instruction would change it to a different address before it was actually referenced.

**Comment by xerub** [comment]
If I understand correctly, you say that XREF should only be caught at 0000000000100004, but not at 0000000000100000 (though both are ultimately considered XREFs).
__text:0000000000100000                 ADRP            X0, #blah@PAGE ; "hello"
__text:0000000000100004                 ADD             X0, X0, #blah@PAGEOFF ; "hello"
__text:0000000000100008                 RET
__text:0000000000100008 ; ---------------------------------------------------------------------------
__text:000000000010000C                 ALIGN 0x1000
__text:0000000000101000 blah            DCB "hello",0           ; DATA XREF: __text:0000000000100000
__text:0000000000101000                                         ; __text:0000000000100004

But isn't 0000000000100000 a valid XREF in this (admittedly contrived) context?
__text:0000000000100000                 ADRP            X0, #blah@PAGE ; "hello"
__text:0000000000100004                 RET
__text:0000000000100004 ; ---------------------------------------------------------------------------
__text:0000000000100008                 ALIGN 0x1000
__text:0000000000101000 blah            DCB "hello",0           ; DATA XREF: __text:0000000000100000

The point of the patchfinder was to catch an XREF as soon as the target address is hit. Having it point to the precise instruction (semantically speaking) was not that important, because XREFs were usually used as anchors form which further scouting took place (backwards or forwards).

Now, your proposed behavior can be done by just adding a continue; after handling ADRP. I don't mind merging your PR, but does it make any difference in real-life?

**Comment by sbingner** [comment]
Yes, it could be but I didn’t find anywhere that it used an ADRP without a corresponding ADR.

A safer fix might be to test if the next instruction is an ADR or not perhaps?

There were a few kernel versions where a string being searched for was on a page address with 0 offset.  It would fail because it found anything else in that page before getting to the actual reference where it had an ADR xn, foo@PAGEOFF because it matched before that on somwthing like ADRP xn, bar@PAGE

I need to look at it again, I thought there was a reason I didn’t use continue.

**Comment by sbingner** [comment]
Can confirm a continue at the end of the adrp match is a better way to do it yes

**Comment by xerub** [comment]
Your case where it was failing, was it a real ADRP/ADD? Then I guess subsequent parsing was failing.

Or was it:
ADRP Xn
...
LDR Xm, [Xn, ...]

**Comment by sbingner** [comment]
I’ll find the actual code that was failing when I get home...  it was for shenanigans on a specific iOS version

**Comment by sbingner** [comment]
String in iPhone7 11.3:
> com.apple.security.sandbox:__cstring:FFFFFFF006147000 aShenanigansBui DCB 0x22,"shenanigans!",0x22,"@/BuildRoot/Library/Caches/com.apple.xb"`

when it searched for the ref it would get 

> com.apple.security.sandbox:__text:FFFFFFF006B2A104 ADRP            X0, #aTruncated@PAGE
> com.apple.security.sandbox:__text:FFFFFFF006B2A108                 ADD             X0, X0, #aTruncated@PAGEOFF

instead of the actual ref at 
> com.apple.security.sandbox:__text:FFFFFFF006B35778                 ADRP            X0, #aShenanigansBui@PAGE
> com.apple.security.sandbox:__text:FFFFFFF006B3577C                 ADD             X0, X0, #aShenanigansBui@PAGEOFF

because the string:
> com.apple.driver.AppleMesaSEPDriver:GAP_hidden:FFFFFFF006147A80 aTruncated      DCB "truncated",0

has an address in the page `FFFFFFF006147000` and is referenced sooner.

I found it due to the Unc0ver issue: https://github.com/pwn20wndstuff/Undecimus/issues/224

**Comment by xerub** [comment]
Fixed now. Thanks!

**Pull request merged**
